# This is a basic workflow to help you get started with Actions

name: poi-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ foo ]
  pull_request:
    branches: [ foo ]

env:
  registry: openhackdevops10478acr.azurecr.io
  acrRepoPoi: 'devopsoh/api-poi'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Docker login
        run: docker login $registry -u ${{ secrets.ACR_USER }} -p ${{ secrets.ACR_KEY }}

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
        uses: docker/build-push-action@v1.1.1
        with:
          # Docker repository to tag the image with
          repository: $acrRepoPoi
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: GH$GITHUB_RUN_NUMBER
          # Path to the build context
          path: ./apis/poi/web
          # Always attempt to pull a newer version of the image
          always_pull: true
          # Whether to push the image
          push: true
